export const ActionTypes = {
    SET_USER_NAME:"SET_USER_NAME",
    SET_USER_AGE:"SET_USER_AGE",
    SET_USER_MODAL:"SET_USER_MODAL",
    SET_USER_LIST:"SET_USER_LIST",
    DELETE_USER:"DELETE_USER",
    SET_EDIT_MODAL:"SET_EDIT_MODAL",
    UPDATE_USER:"UPDATE_USER"
};